Remde

diff --git a/SCRIPT-v8.5x/VPS-AGN/menu b/SCRIPT-v8.5x/VPS-AGN/menu
--- a/SCRIPT-v8.5x/VPS-AGN/menu
+++ b/SCRIPT-v8.5x/VPS-AGN/menu
@@ -633,7 +633,347 @@ menu3() {
     export -f lacasita
     lacasita
     msg -bar
-    echo -e "	\e[97m\e[1;100mPROTOCOLOS\e[0m		  \e[97m\e[41mHERRAMIENTAS\e[0m"
+    echo -e "	\e[97m\e[1;100mPROTOCOLOS\e[0m		  \e[97m\e[41m#--- CHEKER USER APKS
+chekc_users() {
+  clear && clear
+  msg -bar2
+  msg -tit
+  msg -bar2
+  msg -ama "                   CHECK USER APKS"
+  msg -bar2
+  verif_ptrs() {
+    porta=$1
+    PT=$(lsof -V -i tcp -P -n | grep -v "ESTABLISHED" | grep -v "COMMAND" | grep "LISTEN")
+    for pton in $(echo -e "$PT" | cut -d: -f2 | cut -d' ' -f1 | uniq); do
+      svcs=$(echo -e "$PT" | grep -w "$pton" | awk '{print $1}' | uniq)
+      [[ "$porta" = "$pton" ]] && {
+        echo -e "\n\033[1;31mPUERTO \033[1;33m$porta \033[1;31mEN USO PELO \033[1;37m$svcs\033[0m"
+        sleep 3
+        fun_initcheck
+      }
+    done
+  }
+
+  fun_bar() {
+    comando[0]="$1"
+    comando[1]="$2"
+    (
+      [[ -e $HOME/fim ]] && rm $HOME/fim
+      ${comando[0]} >/dev/null 2>&1
+      ${comando[1]} >/dev/null 2>&1
+      touch $HOME/fim
+    ) >/dev/null 2>&1 &
+    tput civis
+    echo -ne "\033[1;33m       ESPERE \033[1;37m- \033[1;33m["
+    while true; do
+      for ((i = 0; i < 18; i++)); do
+        echo -ne "\033[1;31m#"
+        sleep 0.1s
+      done
+      [[ -e $HOME/fim ]] && rm $HOME/fim && break
+      echo -e "\033[1;33m]"
+      sleep 1s
+      tput cuu1
+      tput dl1
+      echo -ne "\033[1;33m       ESPERE \033[1;37m- \033[1;33m["
+    done
+    echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
+    tput cnorm
+  }
+
+  fun_initcheck() {
+
+    var_sks1=$(ps x | grep "checkuser" | grep -v grep >/dev/null && echo -e "\033[1;32m ON " || echo -e "\033[1;31mOFF ")
+    var_sks2=$(ps x | grep "4gcheck" | grep -v grep >/dev/null && echo -e "\033[1;32m   ON " || echo -e "\033[1;31m  OFF ")
+    echo ""
+    echo -e "     \033[1;31m[\033[1;36m 1 \033[1;31m] \033[1;37m鈥� \033[1;33mACTIVAR CHECKUSER (BASICO) $var_sks1 \033[0m"
+    echo -e "     \033[1;31m[\033[1;36m 2 \033[1;31m] \033[1;37m鈥� \033[1;33mACTIVAR CHECKUSER (PLUS) $var_sks2 \033[0m"
+    echo -e "     \033[1;31m[\033[1;36m 0 \033[1;31m] \033[1;37m鈥� \033[1;31mCANCELAR\033[0m"
+    echo ""
+    echo -ne "\033[1;32mQUE DESEA REALIZAR \033[1;33m?\033[1;37m "
+    read resposta
+    if [[ "$resposta" = '1' ]]; then
+      if ps x | grep -w checkuser | grep -v grep 1>/dev/null 2>/dev/null; then
+        echo ""
+        echo -e "\E[1;92m                 CHECKUSER(BASICO)              \E[0m"
+        echo ""
+        fun_stopbad() {
+          screen -r -S "checkuser" -X quit
+          [[ $(grep -wc "check.py" /etc/autostart) != '0' ]] && {
+            sed -i '/check.py/d' /etc/autostart
+          }
+          sleep 1
+          screen -wipe >/dev/null
+        }
+        echo -e "           \033[1;91mDESACTIVANDO CHECKUSER(BASICO)\033[1;33m"
+        fun_stopbad
+        echo ""
+        msg -bar
+        read -t 60 -n 1 -rsp $'\033[1;39m       << Presiona enter para Continuar >>\n'
+        herramientas_fun
+      else
+        echo ""
+        echo -e "\e[48;5;40m\e[38;5;0m            ACTIVANDO CHECKUSER (BASICO)           \E[0m"
+        echo ""
+        echo -ne "\033[1;97mCUAL \033[1;91mPUERTO \033[1;32mDESEA ULTILIZAR \033[1;33m?\033[1;37m: "
+        read porta
+        [[ $porta != ?(+|-)+([0-9]) ]] && {
+          echo ""
+          echo -e "\033[1;31mPuerto Invalido!"
+          sleep 3
+          clear
+          fun_initcheck
+        }
+        verif_ptrs $porta
+        fun_check() {
+          screen -dmS checkuser python3 /etc/SCRIPT-v8.5x/VPS-AGN/protocols/check.py $porta 1
+          [[ $(grep -wc "check.py" /etc/autostart) = '0' ]] && {
+            echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'ws' -X quit;  screen -dmS checkuser python3 /etc/SCRIPT-v8.5x/VPS-AGN/protocols/check.py $porta 1; }" >>/etc/autostart
+          } || {
+            sed -i '/check.py/d' /etc/autostart
+            echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'ws' -X quit;  screen -dmS checkuser python3 /etc/SCRIPT-v8.5x/VPS-AGN/protocols/check.py $porta 1; }" >>/etc/autostart
+          }
+          sleep 1
+        }
+
+        fun_check2() {
+          screen -dmS checkuser python3 /etc/SCRIPT-v8.5x/VPS-AGN/protocols/4gcheck.py $porta 2
+          [[ $(grep -wc "4gcheck.py" /etc/autostart) = '0' ]] && {
+            echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'ws' -X quit;  screen -dmS checkuser python3 /etc/SCRIPT-v8.5x/VPS-AGN/protocols/check.py $porta 2; }" >>/etc/autostart
+          } || {
+            sed -i '/4gcheck.py/d' /etc/autostart
+            echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'ws' -X quit;  screen -dmS checkuser python3 /etc/SCRIPT-v8.5x/VPS-AGN/protocols/check.py $porta 2; }" >>/etc/autostart
+          }
+          sleep 1
+        }
+        echo ""
+        echo -e "\033[1;97mSELECIONE TIPO DE FORMATO.\033[0m"
+        echo ""
+        echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m鈥� \033[1;33mFORMATO YYYY/MM/DD (MAS COMUN)\033[0m"
+        echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m鈥� \033[1;33mFORMATO DD/MM/YYYY\033[0m"
+        echo ""
+        echo -ne "\033[1;36mOpcion: \033[1;37m"
+        read resposta
+        if [[ "$resposta" = '1' ]]; then
+          echo ""
+          fun_bar 'fun_check'
+        elif [[ "$resposta" = '2' ]]; then
+          echo ""
+          fun_bar 'fun_check2'
+        else
+          echo ""
+          echo -e "\033[1;31mOpcion Invalida !\033[0m"
+          sleep 3
+          fun_initcheck
+        fi
+        echo ""
+        echo -e "\033[1;32m     CHECKUSER(BASICO) ACTIVADO CON EXITO\033[1;33m"
+        echo ""
+        echo -e "     URL: \033[1;97mhttp://$(meu_ip):$porta/checkUser"
+        echo ""
+        msg -bar
+        read -t 60 -n 1 -rsp $'\033[1;39m       << Presiona enter para Continuar >>\n'
+        herramientas_fun
+      fi
+    elif [[ "$resposta" = '2' ]]; then
+      if ps x | grep -w 4gcheck | grep -v grep 1>/dev/null 2>/dev/null; then
+        echo ""
+        echo -e "\E[1;92m                  CHECKUSER(PLUS)              \E[0m"
+        echo ""
+        fun_stopbad() {
+          screen -r -S "4gcheck" -X quit
+          [[ $(grep -wc "4gcheck.py" /etc/autostart) != '0' ]] && {
+            sed -i '/4gcheck.py/d' /etc/autostart
+          }
+          sleep 1
+          screen -wipe >/dev/null
+        }
+        echo -e "           \033[1;91mDESACTIVANDO CHECKUSER(PLUS)\033[1;33m"
+        fun_stopbad
+        echo ""
+        msg -bar
+        read -t 60 -n 1 -rsp $'\033[1;39m       << Presiona enter para Continuar >>\n'
+        herramientas_fun
+      else
+        echo ""
+        echo -e "\e[48;5;40m\e[38;5;0m            ACTIVANDO CHECKUSER (PLUS)           \E[0m"
+        echo ""
+        echo -ne "\033[1;97mCUAL \033[1;91mPUERTO \033[1;32mDESEA ULTILIZAR \033[1;33m?\033[1;37m: "
+        read porta
+        [[ $porta != ?(+|-)+([0-9]) ]] && {
+          echo ""
+          echo -e "\033[1;31mPuerto Invalido!"
+          sleep 3
+
+          fun_initcheck
+        }
+        verif_ptrs $porta
+        fun_udpon() {
+          screen -dmS 4gcheck python3 /etc/SCRIPT-v8.5x/VPS-AGN/protocols/4gcheck.py $porta
+          [[ $(grep -wc "4gcheck.py" /etc/autostart) = '0' ]] && {
+            echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'ws' -X quit;  screen -dmS checkuser python3 /etc/SCRIPT-v8.5x/VPS-AGN/protocols/4gcheck.py $porta; }" >>/etc/autostart
+          } || {
+            sed -i '/check.py/d' /etc/autostart
+            echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'ws' -X quit;  screen -dmS checkuser python3 /etc/SCRIPT-v8.5x/VPS-AGN/protocols/4gcheck.py $porta; }" >>/etc/autostart
+          }
+          sleep 1
+        }
+        echo ""
+        fun_bar 'fun_udpon'
+        echo ""
+        echo -e "\033[1;32m       CHECKUSER(PLUS) ACTIVADO CON EXITO\033[1;33m"
+        echo ""
+        echo -e "     URL: \033[1;97mhttp://$(meu_ip):$porta/checkUser"
+        echo ""
+        msg -bar
+        read -t 60 -n 1 -rsp $'\033[1;39m       << Presiona enter para Continuar >>\n'
+        herramientas_fun
+      fi
+    elif [[ "$resposta" = '0' ]]; then
+      msg -bar
+      read -t 60 -n 1 -rsp $'\033[1;39m       << Presiona enter para Continuar >>\n'
+      herramientas_fun
+    else
+      echo ""
+      echo -e "\033[1;31mOpcao invalida !\033[0m"
+      sleep 1
+      fun_initcheck
+    fi
+  }
+
+  inst_depedencias() {
+    # ehck installed pip3
+    if ! [ -x "$(command -v pip3)" ]; then
+      echo 'Error: pip3 no esta instalado.' >&2
+      echo 'Instale pip3 .' >&2
+
+      if ! apt-get install -y python3-pip; then
+        echo 'Erro ao instalar pip3' >&2
+        exit 1
+      else
+        echo 'Instalado pip3 con exito'
+      fi
+    fi
+
+    # install flask
+    pip3 install flask >/dev/null 2>&1
+
+    # download check.py
+    [[ -e "/etc/SCRIPT-v8.5x/VPS-AGN/protocols/check.py" ]] && {
+      sleep 0.1
+    } || {
+      wget -O /etc/SCRIPT-v8.5x/VPS-AGN/protocols/check.py https://raw.githubusercontent.com/thefather12/VPS-SV/main/SCRIPT-v8.5x/VPS-AGN/protocols/check.py &>/dev/null
+      chmod +rwx /etc/SCRIPT-v8.5x/VPS-AGN/protocols/check.py
+    }
+
+    [[ -e "/etc/SCRIPT-v8.5x/VPS-AGN/protocols/4gcheck.py" ]] && {
+      sleep 0.1
+    } || {
+      wget -O /etc/SCRIPT-v8.5x/VPS-AGN/protocols/4gcheck.py https://raw.githubusercontent.com/thefather12/VPS-SV/main/SCRIPT-v8.5x/VPS-AGN/protocols/4gcheck.py &>/dev/null
+      chmod +rwx /etc/SCRIPT-LATAM/filespy/4gcheck.py
+    }
+
+    [[ -e "/bin/check" ]] && {
+      sleep 0.1
+    } || {
+      wget -O /bin/check https://raw.githubusercontent.com/thefather12/VPS-SV/main/SCRIPT-v8.5x/VPS-AGN/protocols/check &>/dev/null
+      chmod 777 /bin/check
+    }
+  }
+
+  [[ -e "/etc/SCRIPT-v8.5x/VPS-AGN/protocols/check.py" ]] && [[ -e "/etc/SCRIPT-v8.5x/VPS-AGN/protocols/4gcheck.py" ]] && [[ -e "/bin/check" ]] && {
+    fun_initcheck
+  } || {
+
+    echo -e "\n\033[1;97m     SE INSTALARA EL WEBHOOK  DE APK PERSONALES \033[0m"
+    echo ""
+    echo -ne "\033[1;32m     Proceder con la Instalacion ? \033[1;33m[\033[1;97ms \033[1;37m/ n\033[1;33m]:\033[1;32m "
+    read resposta
+    [[ "$resposta" = 's' ]] && {
+      echo -e "\n\033[1;32m                 Instalando CHECKUSER"
+      echo ""
+      fun_bar 'inst_depedencias'
+      fun_initcheck
+    } || {
+      msg -bar
+      read -t 60 -n 1 -rsp $'\033[1;39m       << Presiona enter para Continuar >>\n'
+      herramientas_fun
+    }
+  }
+
+  msg -bar
+  read -t 60 -n 1 -rsp $'\033[1;39m       << Presiona enter para Continuar >>\n'
+  herramientas_fun
+
+}
+chekc_online() {
+
+  ##-->> DESCARGAR ARHIVO
+
+  if [ -e "/etc/SCRIPT-v8.5x/VPS-AGN/protocols/onlineapp.sh" ]; then
+    clear && clear
+    msg -bar2
+    msg -tit
+    msg -bar2
+    msg -ama "               CHEKER ONLINES APKS"
+    msg -bar2
+    echo -e "\033[1;97m            ELIMINANDO ONLINES APKS \033[0m"
+    rm -rf /etc/SCRIPT-v8.5x/VPS-AGN/protocols/onlineapp.sh
+    service apache2 stop &>/dev/null
+    eliminar_tarea_crontab() {
+      tarea="$1"
+      crontab -l >archivo_crontab
+      sed -i "/$tarea/d" archivo_crontab
+      crontab archivo_crontab
+      rm archivo_crontab
+    }
+    eliminar_tarea_crontab "*/1 * * * * root /bin/bash /etc/SCRIPT-v8.5x/VPS-AGN/protocols/onlineapp.sh"
+     service cron reload &>/dev/null
+  else
+    clear && clear
+    msg -bar2
+    msg -tit
+    msg -bar2
+    msg -ama "               CHEKER ONLINES APKS"
+    msg -bar2
+    echo -e "\033[1;97m     SE INSTALARAN LOS PAQUETES CORRESPONDIENTES \033[0m"
+    apt-get update &>/dev/null
+    apt-get install apache2 -y &>/dev/null
+    fun_bar "apt-get install apache2 -y &>/dev/null "
+    sed -i 's/Listen 80/Listen 8888/' /etc/apache2/ports.conf
+    sed -i 's/:80>/:8888>/' /etc/apache2/sites-available/000-default.conf
+    mkdir -p /var/www/html/server
+    wget -O /etc/SCRIPT-v8.5x/VPS-AGN/protocols/onlineapp.sh https://raw.githubusercontent.com/NT-GIT-HUB/StatusServer/main/onlineapp.sh &>/dev/null
+    chmod +x /etc/SCRIPT-v8.5x/VPS-AGN/protocols/onlineapp.sh
+    /etc/SCRIPT-v8.5x/VPS-AGN/protocols/onlineapp.sh &>/dev/null
+    agregar_tarea_cron() {
+      local script="/etc/SCRIPT-v8.5x/VPS-AGN/protocols/onlineapp.sh"
+      local tarea="*/1 * * * * root /bin/bash ${script}"
+      echo "${tarea}" >>/etc/crontab
+    }
+    agregar_tarea_cron
+    service cron reload &>/dev/null
+    ufw allow 8888/tcp &>/dev/null
+    service apache2 restart &>/dev/null
+    check_apache_port() {
+      if netstat -tln | grep -q :8888; then
+        echo ""
+        echo -e "\n\033[1;32m             CHECK ONLINES STATUS \033[1;32m ON \033[1;33m"
+      else
+        echo ""
+        echo -e "\n\033[1;32m             CHECK ONLINES STATUS \033[1;31mOFF \033[1;33m"
+      fi
+    }
+    check_apache_port
+    echo -e "  URL: \033[1;97mhttp://$(meu_ip):8888:/server/online"
+
+  fi
+  msg -bar
+  read -t 60 -n 1 -rsp $'\033[1;39m       << Presiona enter para Continuar >>\n'
+  
+  
+  herramientas_fun
+}\e[0m"
     msg -bar
     echo -e "\e[1;93m[\e[92m1\e[93m]$(msg -verm2 "➛ ")$(msg -azu "BADVPN        ${inst[badvpn]}")  \e[1;93m[\e[92m11\e[93m]$(msg -verm2 "➛ ")$(msg -azu "ARCHIVOS EN LINEA")"
     echo -e "\e[1;93m[\e[92m2\e[93m]$(msg -verm2 "➛ ")$(msg -azu "HTTP-PYTHON   $plox")  \e[1;93m[\e[92m12\e[93m]$(msg -verm2 "➛ ")$(msg -azu "FIREWALL")"
@@ -732,6 +1072,8 @@ extra() {
     echo -e " \e[1;93m[\e[92m11\e[93m]$(msg -verm2 "➛ ")$(msg -azu "CAMBIAR CONTRASEÑA ROOT")"
     echo -e " \e[1;93m[\e[92m12\e[93m]$(msg -verm2 "➛ ")$(msg -azu "AGREGAR ROOT A GoogleCloud Y Amazon")"
     echo -e " \e[1;93m[\e[92m13\e[93m]$(msg -verm2 "➛ ")$(msg -azu "AUTENTICAR SQUID")"
+    echo -e " \e[1;93m[\e[92m14\e[93m]$(msg -verm2 "➛ ")$(msg -azu "CHECKUSER APKS MOD")"
+    echo -e " \e[1;93m[\e[92m15\e[93m]$(msg -verm2 "➛ ")$(msg -azu "USER ONLINES")"
     echo -e " \e[1;93m[\e[92m0\e[93m]$(msg -verm2 " ➛ ")$(msg -azu "REGRESAR")"
     msg -bar
     echo -ne " ►\e[1;37m Seleccione una opción: \e[33m " && read select
@@ -753,6 +1095,8 @@ extra() {
     11) cambiopass ;;
     12) rootpass ;;
     13) ${SCPfrm}/squidpass.sh ;;
+    14) chekc_users ;;
+    15) chekc_online ;;
     *) ;;
     esac
 }
